### ISSUE TITLE
Limpieza de los datos

### ISSUE THREAD

**Issue by atos-wk** [prope-2020-gh-classroom/practica-final-por-equipos-verano-2020-itam-atos-wk#3]
- [x] Revisar la cantidad de NA.
- [x] Eliminar categorías de poca frecuencia.
- [x] Delimitar los registros a la CDMX
- [x] Guardar los resultados

**Comment by Acturio** [comment]
Los datos de delitos de la Ciudad de México se encuentran limpios y delimitados
